#!/bin/sh
# This hook is always fired, if we need to do live modification on the usb stick or extra tasks, do them here.
case "$1" in
slot-post-install)
        # only rootfs needs to be handled
        test "$RAUC_SLOT_CLASS" = "rootfs" || exit 0

        """
        <MartB>: 23.02.2025
        The following migrations should be removed once all sensors are migrated to the new version.
        """
        # Migrate apogee data folder if it exists
        if [ -d /data/config/apogee ]; then
            # Move without creating "apogee" in target directory
            echo "migration: moving data folder from apogee to client."
            mv -T /data/config/apogee /data/config/client
        fi

        # Check if tune2fs is installed if yes, check if we can relabel the data stick
        RELABEL_DISCOSAT=(tune2fs -L leocommon-data LABEL=discosat-data)
        if [ -x "$(command -v tune2fs)" ] && ${RELABEL_DISCOSAT[@]} >/dev/null 2>&1; then
            echo 'migration: relabeled discosat-data stick to leocommon-data.'
            # to revert it, run tune2fs -L discosat-data LABEL=leocommon-data
        fi
        ;;
slot-pre-install)
        # only rootfs needs to be handled
        test "$RAUC_SLOT_CLASS" = "rootfs" || exit 0
        ;;
install-check)
        # Check if RAUC_SYSTEM_COMPATIBLE contains satos-rpi4-64 or satos-rpi5-64
        if [[ "$RAUC_SYSTEM_COMPATIBLE" =~ satos-rpi4-64 ]] || [[ "$RAUC_SYSTEM_COMPATIBLE" =~ satos-rpi5-64 ]]; then
            # Check if RAUC_MF_COMPATIBLE contains satos-rpi64
            if [[ "$RAUC_MF_COMPATIBLE" =~ satos-rpi64 ]]; then
                echo "Compatible values validated successfully"
                exit 0
            else
                echo "RAUC_MF_COMPATIBLE does not contain satos-rpi64!" 1>&2
                exit 10
            fi
        else
            # Check if RAUC_SYSTEM_COMPATIBLE matches RAUC_MF_COMPATIBLE
            if [[ "$RAUC_SYSTEM_COMPATIBLE" != "$RAUC_MF_COMPATIBLE" ]]; then
                echo "Compatible string does not match!" 1>&2
                exit 10
            fi
        fi
        ;;
*)
        exit 1
        ;;
esac

exit 0
