################################################################################
#
# soapysdr-lime
#
################################################################################

SOAPYSDR_LIME_VERSION = a580f9cbc7bec9478ac08d93513690714a1753dd
SOAPYSDR_LIME_SITE = $(call github,myriadrf,LimeSuiteNG,$(SOAPYSDR_LIME_VERSION))
SOAPYSDR_LIME_LICENSE = GPL3.0
SOAPYSDR_LIME_LICENSE_FILES = COPYING
SOAPYSDR_LIME_DEPENDENCIES = python3 host-swig soapysdr boost libusb
SOAPYSDR_LIME_INSTALL_STAGING = NO
SOAPYSDR_LIME_SUPPORTS_IN_SOURCE_BUILD = NO
SOAPYSDR_LIME_CONF_OPTS = \
	-DBUILD_CLI=OFF \
    -DBUILD_GUI=OFF \
    -DBUILD_DOCS=OFF \
    -DENABLE_UNIT_TESTS=OFF \
	-DLIMESUITENG_PCIE=OFF \
	-DBUILD_DRIVERS_LIMEPCIE=OFF \
	-DBUILD_PLUGINS_AMARISOFT=OFF \
	-DUDEV_RULES_RELOAD_ON_INSTALL=OFF \
	-DINSTALL_DEVELOPMENT=OFF

ifeq ($(BR2_PACKAGE_HAS_UDEV),y)
SOAPYSDR_LIME_CONF_OPTS += -DINSTALL_UDEV_RULES=ON
SOAPYSDR_LIME_DEPENDENCIES += udev
else
SOAPYSDR_LIME_CONF_OPTS += -DINSTALL_UDEV_RULES=OFF
endif

$(eval $(cmake-package))
